# Generated by Django 4.0.3 on 2022-03-16 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='دسته بندی پدر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندیها',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('priority', models.CharField(choices=[('HIG', 'بالا'), ('MED', 'متوسط'), ('LOW', 'پایین')], default='MED', max_length=3, verbose_name='الویت')),
                ('completed', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='api.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'کار',
                'verbose_name_plural': 'کار\u200cها',
            },
        ),
    ]
