# Generated by Django 4.0.3 on 2022-03-29 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='api.category', verbose_name='دسته بندی'),
        ),
    ]
